language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update
    - platformio lib -g install 5763

script:
    - platformio ci --lib="." --board=uno "./examples/timers/WeatherMeters_AVR"

notifications:
  email:
    on_success: change
    on_failure: change
